version: "3"
services:
  front-end:
    stdin_open: true
    tty: false
    build: .
    ports:
      - "8060:8060"
    volumes:
      - ./src:/front-end/src
  mastodon_frontend:
    build:
      context: ./mastodon_front_end
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
