---
- hosts: 127.0.0.1
  become: yes
  tasks:
  - name: Install apt dependencies
    apt:
      update_cache: yes
      name:
        - ca-certificates
        - curl
        - gnupg
      state: present
  
  - name: Create Docker keyring directory
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Add Docker's official GPG key
    command:
      cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    args:
      warn: false # to ignore the curl pipe warning

  - name: Set Docker keyring permission
    file:
      path: /etc/apt/keyrings/docker.gpg
      mode: '0644'

  - name: Set up Docker repository
    shell: |
      echo \
      "deb [arch=\"$(dpkg --print-architecture)\" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      \"$($. /etc/os-release && echo \"$VERSION_CODENAME\")\" stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    args:
      executable: /bin/bash

  - name: Install Docker, python
    apt:
      update_cache: yes
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present

  - name: Install required Python packages
    pip:
      name:
        - docker
        - couchdb
        - configparser
        - Mastodon.py
      executable: pip3

  - name: Build Docker images
    command:
      cmd: docker build -t {{ item.name }} {{ item.path }}
    loop:
      - { name: 'aus-stream', path: '/home/ubuntu/COMP90024-Project/mastodon/aus-stream/' }
      - { name: 'aus-social-stream', path: '/home/ubuntu/COMP90024-Project/mastodon/aus-stream' }

  - name: Run Docker container aus-stream
    docker_container:
      name: aus-stream-container
      image: aus-stream
      published_ports:
        - "8070:81"
      state: started

  - name: Run Docker container aus-social-stream
    docker_container:
        name: aus-social-stream-container
        image: aus-social-stream
        published_ports:
          - "7070:81"
        state: started