---
- hosts: all
  become: yes
  tasks:
  - name: Install Docker, python
    apt:
      update_cache: yes
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        - python3-pip
        - python3
      state: present

  - name: Install required Python packages
    pip:
      name:
        - couchdb
        - configparser
        - Mastodon.py
      executable: pip3

  - name: Build Docker images
    command:
      cmd: docker build -t {{ item.name }} {{ item.path }}
    loop:
      - { name: 'aus-stream', path: '/home/ubuntu/COMP90024-Project/mastodon/aus-stream/Dockerfile' }
      - { name: 'aus-social-stream', path: '/home/ubuntu/COMP90024-Project/mastodon/aus-social-stream/Dockerfile' }

  - name: Run Docker container aus-stream
    docker_container:
      name: aus-stream-container
      image: aus-stream
      published_ports:
        - "8070:81"
      state: started

  - name: Run Docker container aus-social-stream
    docker_container:
        name: aus-social-stream-container
        image: aus-social-stream
        published_ports:
          - "7070:81"
        state: started