---
- hosts: 127.0.0.1
  become: yes
  vars:
    mastodon_base_path: "/home/ubuntu/mastodon"
  tasks:
    - name: Ensure Docker Compose is installed
      pip:
        name: docker-compose
        executable: pip3
        state: present

    - name: Run Docker Compose
      docker_compose:
        project_src: "{{ mastodon_base_path }}"
        state: present
---

