---
- hosts: 127.0.0.1
  become: yes
  vars:
    mastodon_base_path: "/home/ubuntu/mastodon"
  tasks:

  - name: Remove existing Docker packages
    apt:
      name: 
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: absent

  - name: Install prerequisite packages
    apt:
      name: 
        - ca-certificates
        - curl
        - gnupg
      state: present

  - name: Create the directory for Docker keyring
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Download Docker's official GPG key and move it to the keyring directory
    shell:
      cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

  - name: Change permission of Docker keyring
    file:
      path: /etc/apt/keyrings/docker.gpg
      mode: '0644'

  - name: Add Docker's APT repository
    shell:
      cmd: |
        echo \
        "deb [arch=\"$(dpkg --print-architecture)\" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        jammy stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install Docker
    apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present

  - name: Ensure Docker service is running
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Install Docker Python package
    pip:
      name: docker
      executable: pip3

  - name: Build Docker images
    docker_image:
      name: "{{ item.name }}"
      build:
        path: "{{ mastodon_base_path }}/{{ item.path }}"
      source: build
    loop:
      - { name: 'aus-nlp-stream', path: 'aus-nlp-stream' }
      - { name: 'aus-social-nlp-stream', path: 'aus-social-nlp-stream' }

  - name: Run Docker container aus-stream
    docker_container:
      name: aus-nlp-stream-container
      image: aus-nlp-stream
      published_ports:
        - "8070:81"
      state: started

  - name: Run Docker container aus-social-stream
    docker_container:
      name: aus-social-nlp-stream-container
      image: aus-social-nlp-stream
      published_ports:
        - "7070:81"
      state: started
...
