---
- hosts: 127.0.0.1
  become: yes
  vars:
    targetnode: "{{ ansible_default_ipv4.address }}"

  tasks:
    - name: Gather facts
      setup:

    - name: Get node _rev using curl
      shell: >
        curl -X GET "http://{{ user }}:{{ db_pass }}@{{ masternode }}:5984/_node/_local/_nodes/couchdb@{{ targetnode }}"
      register: rev_result
      args:
        warn: no

    - name: Extract _rev from result
      set_fact:
        rev: "{{ (rev_result.stdout | from_json)._rev }}"

    - name: Delete node from cluster using curl
      shell: >
        curl -X DELETE "http://{{ user }}:{{ db_pass }}@{{ masternode }}:5984/_node/_local/_nodes/couchdb@{{ targetnode }}?rev={{ rev }}"
      register: delete_result
      args:
        warn: no

    - name: Print delete result
      debug:
        var: delete_result

    - name: Stop and remove Docker container
      docker_container:
        name: "couchdb{{ targetnode }}"
        state: absent
